package com.dingtao.common.core.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingtao.common.bean.LoginBean;
import com.dingtao.common.bean.UserInfo;

import com.dingtao.common.core.db.LoginBeanDao;
import com.dingtao.common.core.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final LoginBeanDao loginBeanDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(LoginBean.class, loginBeanDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        loginBeanDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
