package com.dingtao.common.core.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dingtao.common.bean.LoginBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOGIN_BEAN".
*/
public class LoginBeanDao extends AbstractDao<LoginBean, Long> {

    public static final String TABLENAME = "LOGIN_BEAN";

    /**
     * Properties of entity LoginBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SessionId = new Property(1, String.class, "sessionId", false, "SESSION_ID");
        public final static Property NickName = new Property(2, String.class, "nickName", false, "NICK_NAME");
        public final static Property UserName = new Property(3, String.class, "userName", false, "USER_NAME");
        public final static Property JiGuangPwd = new Property(4, String.class, "jiGuangPwd", false, "JI_GUANG_PWD");
        public final static Property HeadPic = new Property(5, String.class, "headPic", false, "HEAD_PIC");
        public final static Property Sex = new Property(6, int.class, "sex", false, "SEX");
        public final static Property Age = new Property(7, String.class, "age", false, "AGE");
        public final static Property Height = new Property(8, String.class, "height", false, "HEIGHT");
        public final static Property Weight = new Property(9, String.class, "weight", false, "WEIGHT");
        public final static Property Email = new Property(10, String.class, "email", false, "EMAIL");
        public final static Property WhetherBingWeChat = new Property(11, String.class, "whetherBingWeChat", false, "WHETHER_BING_WE_CHAT");
        public final static Property InvitationCode = new Property(12, String.class, "invitationCode", false, "INVITATION_CODE");
        public final static Property Status = new Property(13, int.class, "status", false, "STATUS");
    }


    public LoginBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LoginBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOGIN_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SESSION_ID\" TEXT," + // 1: sessionId
                "\"NICK_NAME\" TEXT," + // 2: nickName
                "\"USER_NAME\" TEXT," + // 3: userName
                "\"JI_GUANG_PWD\" TEXT," + // 4: jiGuangPwd
                "\"HEAD_PIC\" TEXT," + // 5: headPic
                "\"SEX\" INTEGER NOT NULL ," + // 6: sex
                "\"AGE\" TEXT," + // 7: age
                "\"HEIGHT\" TEXT," + // 8: height
                "\"WEIGHT\" TEXT," + // 9: weight
                "\"EMAIL\" TEXT," + // 10: email
                "\"WHETHER_BING_WE_CHAT\" TEXT," + // 11: whetherBingWeChat
                "\"INVITATION_CODE\" TEXT," + // 12: invitationCode
                "\"STATUS\" INTEGER NOT NULL );"); // 13: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOGIN_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LoginBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(2, sessionId);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(4, userName);
        }
 
        String jiGuangPwd = entity.getJiGuangPwd();
        if (jiGuangPwd != null) {
            stmt.bindString(5, jiGuangPwd);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getSex());
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(8, age);
        }
 
        String height = entity.getHeight();
        if (height != null) {
            stmt.bindString(9, height);
        }
 
        String weight = entity.getWeight();
        if (weight != null) {
            stmt.bindString(10, weight);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(11, email);
        }
 
        String whetherBingWeChat = entity.getWhetherBingWeChat();
        if (whetherBingWeChat != null) {
            stmt.bindString(12, whetherBingWeChat);
        }
 
        String invitationCode = entity.getInvitationCode();
        if (invitationCode != null) {
            stmt.bindString(13, invitationCode);
        }
        stmt.bindLong(14, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LoginBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(2, sessionId);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(4, userName);
        }
 
        String jiGuangPwd = entity.getJiGuangPwd();
        if (jiGuangPwd != null) {
            stmt.bindString(5, jiGuangPwd);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getSex());
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(8, age);
        }
 
        String height = entity.getHeight();
        if (height != null) {
            stmt.bindString(9, height);
        }
 
        String weight = entity.getWeight();
        if (weight != null) {
            stmt.bindString(10, weight);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(11, email);
        }
 
        String whetherBingWeChat = entity.getWhetherBingWeChat();
        if (whetherBingWeChat != null) {
            stmt.bindString(12, whetherBingWeChat);
        }
 
        String invitationCode = entity.getInvitationCode();
        if (invitationCode != null) {
            stmt.bindString(13, invitationCode);
        }
        stmt.bindLong(14, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LoginBean readEntity(Cursor cursor, int offset) {
        LoginBean entity = new LoginBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sessionId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // userName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jiGuangPwd
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // headPic
            cursor.getInt(offset + 6), // sex
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // age
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // height
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // weight
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // email
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // whetherBingWeChat
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // invitationCode
            cursor.getInt(offset + 13) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LoginBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSessionId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJiGuangPwd(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHeadPic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSex(cursor.getInt(offset + 6));
        entity.setAge(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHeight(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWeight(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEmail(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWhetherBingWeChat(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setInvitationCode(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStatus(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LoginBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LoginBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LoginBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
